// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | FaqSectionSlice
  | CardOfferSectionSlice
  | OfferSectionSlice
  | SyllabusSectionSlice
  | DemoSectionSlice
  | AudienceFilterSlice
  | BannerInfoSlice
  | HeroSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Item in *AudienceFilter → Default → Primary → AudienceFilterpositiveList*
 */
export interface AudienceFilterSliceDefaultPrimaryAudiencefilterpositivelistItem {
  /**
   * AudienceFilterItemList field in *AudienceFilter → Default → Primary → AudienceFilterpositiveList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_filter.default.primary.audiencefilterpositivelist[].audiencefilteritemlist
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  audiencefilteritemlist: prismic.KeyTextField;
}

/**
 * Item in *AudienceFilter → Default → Primary → AudienceFilterNegativeList*
 */
export interface AudienceFilterSliceDefaultPrimaryAudiencefilternegativelistItem {
  /**
   * AudienceFilterItemList field in *AudienceFilter → Default → Primary → AudienceFilterNegativeList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_filter.default.primary.audiencefilternegativelist[].audiencefilteritemlist
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  audiencefilteritemlist: prismic.KeyTextField;
}

/**
 * Primary content in *AudienceFilter → Default → Primary*
 */
export interface AudienceFilterSliceDefaultPrimary {
  /**
   * AudienceFilterTitle field in *AudienceFilter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_filter.default.primary.audiencefiltertitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  audiencefiltertitle: prismic.RichTextField;

  /**
   * AudienceFilterText field in *AudienceFilter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_filter.default.primary.audiencefiltertext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  audiencefiltertext: prismic.KeyTextField;

  /**
   * AudiencePositiveListTitle field in *AudienceFilter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_filter.default.primary.audiencepositivelisttitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  audiencepositivelisttitle: prismic.RichTextField;

  /**
   * AudienceNegativeListTitle field in *AudienceFilter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_filter.default.primary.audiencenegativelisttitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  audiencenegativelisttitle: prismic.RichTextField;

  /**
   * AudienceFilterpositiveList field in *AudienceFilter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_filter.default.primary.audiencefilterpositivelist[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  audiencefilterpositivelist: prismic.GroupField<
    Simplify<AudienceFilterSliceDefaultPrimaryAudiencefilterpositivelistItem>
  >;

  /**
   * AudienceFilterNegativeList field in *AudienceFilter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_filter.default.primary.audiencefilternegativelist[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  audiencefilternegativelist: prismic.GroupField<
    Simplify<AudienceFilterSliceDefaultPrimaryAudiencefilternegativelistItem>
  >;
}

/**
 * Default variation for AudienceFilter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudienceFilterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AudienceFilterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AudienceFilter*
 */
type AudienceFilterSliceVariation = AudienceFilterSliceDefault;

/**
 * AudienceFilter Shared Slice
 *
 * - **API ID**: `audience_filter`
 * - **Description**: AudienceFilter
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudienceFilterSlice = prismic.SharedSlice<
  "audience_filter",
  AudienceFilterSliceVariation
>;

/**
 * Item in *BannerInfo → Default → Primary → BannerInfoList*
 */
export interface BannerInfoSliceDefaultPrimaryListaItem {
  /**
   * ItemList field in *BannerInfo → Default → Primary → BannerInfoList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: BannerItemList
   * - **API ID Path**: banner_info.default.primary.lista[].itemlist
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  itemlist: prismic.KeyTextField;
}

/**
 * Primary content in *BannerInfo → Default → Primary*
 */
export interface BannerInfoSliceDefaultPrimary {
  /**
   * BannerInfoTitle field in *BannerInfo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: BannerInfoTitle
   * - **API ID Path**: banner_info.default.primary.bannerinfotitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bannerinfotitle: prismic.RichTextField;

  /**
   * BannerSubtitle field in *BannerInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: BannerSubtitle
   * - **API ID Path**: banner_info.default.primary.bannersubtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bannersubtitle: prismic.KeyTextField;

  /**
   * BannerInfoList field in *BannerInfo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_info.default.primary.lista[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  lista: prismic.GroupField<Simplify<BannerInfoSliceDefaultPrimaryListaItem>>;

  /**
   * supportingText field in *BannerInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: supporting text
   * - **API ID Path**: banner_info.default.primary.supportingtext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  supportingtext: prismic.KeyTextField;
}

/**
 * Default variation for BannerInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BannerInfo*
 */
type BannerInfoSliceVariation = BannerInfoSliceDefault;

/**
 * BannerInfo Shared Slice
 *
 * - **API ID**: `banner_info`
 * - **Description**: BannerInfo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerInfoSlice = prismic.SharedSlice<
  "banner_info",
  BannerInfoSliceVariation
>;

/**
 * Item in *CardOfferSection → Default → Primary → benefitList*
 */
export interface CardOfferSectionSliceDefaultPrimaryBenefitlistItem {
  /**
   * benefitListItem field in *CardOfferSection → Default → Primary → benefitList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_offer_section.default.primary.benefitlist[].benefitlistitem
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  benefitlistitem: prismic.KeyTextField;
}

/**
 * Primary content in *CardOfferSection → Default → Primary*
 */
export interface CardOfferSectionSliceDefaultPrimary {
  /**
   * title field in *CardOfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_offer_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * badgeText field in *CardOfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_offer_section.default.primary.badgetext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badgetext: prismic.KeyTextField;

  /**
   * description field in *CardOfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_offer_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * oldPrice field in *CardOfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_offer_section.default.primary.oldprice
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  oldprice: prismic.KeyTextField;

  /**
   * price field in *CardOfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_offer_section.default.primary.price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;

  /**
   * currency field in *CardOfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_offer_section.default.primary.currency
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  currency: prismic.KeyTextField;

  /**
   * benefitList field in *CardOfferSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_offer_section.default.primary.benefitlist[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  benefitlist: prismic.GroupField<
    Simplify<CardOfferSectionSliceDefaultPrimaryBenefitlistItem>
  >;

  /**
   * supportingText field in *CardOfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_offer_section.default.primary.supportingtext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  supportingtext: prismic.KeyTextField;
}

/**
 * Default variation for CardOfferSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardOfferSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardOfferSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardOfferSection*
 */
type CardOfferSectionSliceVariation = CardOfferSectionSliceDefault;

/**
 * CardOfferSection Shared Slice
 *
 * - **API ID**: `card_offer_section`
 * - **Description**: CardOfferSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardOfferSectionSlice = prismic.SharedSlice<
  "card_offer_section",
  CardOfferSectionSliceVariation
>;

/**
 * Item in *DemoSection → Default → Primary → DemosectionList*
 */
export interface DemoSectionSliceDefaultPrimaryDemosectionlistItem {
  /**
   * DemoSectionItemTitle field in *DemoSection → Default → Primary → DemosectionList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_section.default.primary.demosectionlist[].demosectionitemtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  demosectionitemtitle: prismic.RichTextField;

  /**
   * DemoSectionItemDescription field in *DemoSection → Default → Primary → DemosectionList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_section.default.primary.demosectionlist[].demosectionitemdescription
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  demosectionitemdescription: prismic.KeyTextField;
}

/**
 * Primary content in *DemoSection → Default → Primary*
 */
export interface DemoSectionSliceDefaultPrimary {
  /**
   * DemoSectionTitle field in *DemoSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_section.default.primary.demosectiontitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  demosectiontitle: prismic.RichTextField;

  /**
   * DemosectionList field in *DemoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_section.default.primary.demosectionlist[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  demosectionlist: prismic.GroupField<
    Simplify<DemoSectionSliceDefaultPrimaryDemosectionlistItem>
  >;

  /**
   * DemoSectionQuote field in *DemoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_section.default.primary.demosectionquote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  demosectionquote: prismic.KeyTextField;
}

/**
 * Default variation for DemoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DemoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DemoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DemoSection*
 */
type DemoSectionSliceVariation = DemoSectionSliceDefault;

/**
 * DemoSection Shared Slice
 *
 * - **API ID**: `demo_section`
 * - **Description**: DemoSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DemoSectionSlice = prismic.SharedSlice<
  "demo_section",
  DemoSectionSliceVariation
>;

/**
 * Item in *FaqSection → Default → Primary → FaqAccordion*
 */
export interface FaqSectionSliceDefaultPrimaryFaqaccordionItem {
  /**
   * titleaccordion field in *FaqSection → Default → Primary → FaqAccordion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.faqaccordion[].titleaccordion
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titleaccordion: prismic.KeyTextField;

  /**
   * ItemOne field in *FaqSection → Default → Primary → FaqAccordion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.faqaccordion[].itemone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  itemone: prismic.KeyTextField;

  /**
   * ItemTwo field in *FaqSection → Default → Primary → FaqAccordion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.faqaccordion[].itemtwo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  itemtwo: prismic.KeyTextField;
}

/**
 * Primary content in *FaqSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * title field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * FaqAccordion field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.faqaccordion[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqaccordion: prismic.GroupField<
    Simplify<FaqSectionSliceDefaultPrimaryFaqaccordionItem>
  >;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * HeroTitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: HeroTitle
   * - **API ID Path**: hero.default.primary.HeroTitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  HeroTitle: prismic.RichTextField;

  /**
   * HeroSubTitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: HeroSubTitle
   * - **API ID Path**: hero.default.primary.HeroSubtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  HeroSubtitle: prismic.RichTextField;

  /**
   * HeroBadgeText field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: HeroBadgeText
   * - **API ID Path**: hero.default.primary.HeroBadgeText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  HeroBadgeText: prismic.KeyTextField;

  /**
   * HeroPrice field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: HeroPrice
   * - **API ID Path**: hero.default.primary.HeroPrice
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  HeroPrice: prismic.KeyTextField;

  /**
   * HeroCurrency field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: HeroCurrency
   * - **API ID Path**: hero.default.primary.HeroCurrency
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  HeroCurrency: prismic.KeyTextField;

  /**
   * HeroCtaText field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: HeroCtaText
   * - **API ID Path**: hero.default.primary.HeroCtaText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  HeroCtaText: prismic.KeyTextField;

  /**
   * HeroImg field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.HeroImg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  HeroImg: prismic.ImageField<never>;

  /**
   * HeroTestimonialText field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: HeroTestimonialText
   * - **API ID Path**: hero.default.primary.HeroTestimonialText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  HeroTestimonialText: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *OfferSection → Default → Primary*
 */
export interface OfferSectionSliceDefaultPrimary {
  /**
   * OfferTitle field in *OfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offer_section.default.primary.offertitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  offertitle: prismic.KeyTextField;

  /**
   * OfferSubtitle field in *OfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offer_section.default.primary.offersubtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  offersubtitle: prismic.KeyTextField;

  /**
   * supportingText field in *OfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offer_section.default.primary.supportingtext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  supportingtext: prismic.KeyTextField;

  /**
   * SmallSupportingText field in *OfferSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offer_section.default.primary.smallsupportingtext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  smallsupportingtext: prismic.KeyTextField;
}

/**
 * Default variation for OfferSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OfferSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OfferSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OfferSection*
 */
type OfferSectionSliceVariation = OfferSectionSliceDefault;

/**
 * OfferSection Shared Slice
 *
 * - **API ID**: `offer_section`
 * - **Description**: OfferSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OfferSectionSlice = prismic.SharedSlice<
  "offer_section",
  OfferSectionSliceVariation
>;

/**
 * Item in *SyllabusSection → Default → Primary → AccordionItem*
 */
export interface SyllabusSectionSliceDefaultPrimaryAccordionitemItem {
  /**
   * AccordionItemTitle field in *SyllabusSection → Default → Primary → AccordionItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: title
   * - **API ID Path**: syllabus_section.default.primary.accordionitem[].accordionitemtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  accordionitemtitle: prismic.KeyTextField;

  /**
   * itemlistOne field in *SyllabusSection → Default → Primary → AccordionItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: syllabus_section.default.primary.accordionitem[].itemlistone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  itemlistone: prismic.KeyTextField;

  /**
   * itemlistTwo field in *SyllabusSection → Default → Primary → AccordionItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: syllabus_section.default.primary.accordionitem[].itemlisttwo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  itemlisttwo: prismic.KeyTextField;

  /**
   * itemlistThree field in *SyllabusSection → Default → Primary → AccordionItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: syllabus_section.default.primary.accordionitem[].itemlistthree
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  itemlistthree: prismic.KeyTextField;

  /**
   * itemlistFour field in *SyllabusSection → Default → Primary → AccordionItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: syllabus_section.default.primary.accordionitem[].itemlistfour
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  itemlistfour: prismic.KeyTextField;
}

/**
 * Primary content in *SyllabusSection → Default → Primary*
 */
export interface SyllabusSectionSliceDefaultPrimary {
  /**
   * TitleSection field in *SyllabusSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: syllabus_section.default.primary.titlesection
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  titlesection: prismic.RichTextField;

  /**
   * SubtitleSection field in *SyllabusSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: syllabus_section.default.primary.subtitlesection
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitlesection: prismic.KeyTextField;

  /**
   * AccordionItem field in *SyllabusSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: syllabus_section.default.primary.accordionitem[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  accordionitem: prismic.GroupField<
    Simplify<SyllabusSectionSliceDefaultPrimaryAccordionitemItem>
  >;
}

/**
 * Default variation for SyllabusSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SyllabusSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SyllabusSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SyllabusSection*
 */
type SyllabusSectionSliceVariation = SyllabusSectionSliceDefault;

/**
 * SyllabusSection Shared Slice
 *
 * - **API ID**: `syllabus_section`
 * - **Description**: SyllabusSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SyllabusSectionSlice = prismic.SharedSlice<
  "syllabus_section",
  SyllabusSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AudienceFilterSlice,
      AudienceFilterSliceDefaultPrimaryAudiencefilterpositivelistItem,
      AudienceFilterSliceDefaultPrimaryAudiencefilternegativelistItem,
      AudienceFilterSliceDefaultPrimary,
      AudienceFilterSliceVariation,
      AudienceFilterSliceDefault,
      BannerInfoSlice,
      BannerInfoSliceDefaultPrimaryListaItem,
      BannerInfoSliceDefaultPrimary,
      BannerInfoSliceVariation,
      BannerInfoSliceDefault,
      CardOfferSectionSlice,
      CardOfferSectionSliceDefaultPrimaryBenefitlistItem,
      CardOfferSectionSliceDefaultPrimary,
      CardOfferSectionSliceVariation,
      CardOfferSectionSliceDefault,
      DemoSectionSlice,
      DemoSectionSliceDefaultPrimaryDemosectionlistItem,
      DemoSectionSliceDefaultPrimary,
      DemoSectionSliceVariation,
      DemoSectionSliceDefault,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimaryFaqaccordionItem,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      OfferSectionSlice,
      OfferSectionSliceDefaultPrimary,
      OfferSectionSliceVariation,
      OfferSectionSliceDefault,
      SyllabusSectionSlice,
      SyllabusSectionSliceDefaultPrimaryAccordionitemItem,
      SyllabusSectionSliceDefaultPrimary,
      SyllabusSectionSliceVariation,
      SyllabusSectionSliceDefault,
    };
  }
}
