// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  audience_filter: dynamic(() => import("./AudienceFilter")),
  banner_info: dynamic(() => import("./BannerInfo")),
  card_offer_section: dynamic(() => import("./CardOfferSection")),
  demo_section: dynamic(() => import("./DemoSection")),
  faq_section: dynamic(() => import("./FaqSection")),
  hero: dynamic(() => import("./Hero")),
  offer_section: dynamic(() => import("./OfferSection")),
  syllabus_section: dynamic(() => import("./SyllabusSection")),
};
